# Generated by Django 4.2.28 on 2026-04-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0002_salon_status_paiement_effectue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(choices=[('LOYER', 'Loyer'), ('SALAIRE', 'Salaire'), ('MATERIEL', 'Matériel'), ('EAU_ELECTRICITE', 'Eau / Électricité'), ('PRODUIT', 'Produit coiffure'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='salon.salon')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
