# Generated by Django 4.2.28 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='salon',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
    ]
