# Generated by Django 4.2.28 on 2026-05-07 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_attente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Valide'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('mode_paiement', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Carte'), ('MOBILE', 'Mobile'), ('OTHER', 'Autre')], max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('file_attente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='file_attente.fileattente')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
