"""
Django settings for gestion_coiffure project.

Generated by 'django-admin startproject' using Django 4.2.28.
"""

from pathlib import Path
from decouple import config, Csv
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# ----------------------------------------
# Basic settings
# ----------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY')

DEBUG = str(config("DEBUG", default="False")).lower() in ("1", "true", "yes", "on")

# ----------------------------------------
# ALLOWED_HOSTS & CSRF_TRUSTED_ORIGINS
# ----------------------------------------
_default_allowed_hosts = "127.0.0.1,localhost,192.168.0.138,barber-pro-upue.onrender.com,barberpro.onrender.com"
ALLOWED_HOSTS = config("ALLOWED_HOSTS", default=_default_allowed_hosts, cast=Csv())
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS if host.strip()]

# Add Render hostname automatically
_render_hostname = config("RENDER_EXTERNAL_HOSTNAME", default="").strip()
if _render_hostname and _render_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_hostname)

# Emergency override for testing local
if str(config("ALLOW_ALL_HOSTS", default="False")).lower() in ("1", "true", "yes", "on"):
    ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="https://barber-pro-upue.onrender.com,https://barberpro.onrender.com",
    cast=Csv(),
)

# ----------------------------------------
# Installed apps
# ----------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'frontend',
    'accounts',
    'clients',
    'services',
    'paiements',
    'file_attente',
    'dashbord',
    'salon',
]

# ----------------------------------------
# Middleware
# ----------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'accounts.User'
ROOT_URLCONF = 'gestion_coiffure.urls'
WSGI_APPLICATION = 'gestion_coiffure.wsgi.application'

# ----------------------------------------
# Templates
# ----------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------------------
# Static & Media
# ----------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ----------------------------------------
# Database
# ----------------------------------------
DATABASE_URL = config("DATABASE_URL", default="").strip()
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    _db_name = config("DB_NAME", default="").strip()
    _db_user = config("DB_USER", default="").strip()
    _db_password = config("DB_PASSWORD", default="").strip()
    _db_host = config("DB_HOST", default="localhost").strip()
    _db_port = config("DB_PORT", default="5432").strip()
    if not _db_name or not _db_user or not _db_password:
        raise ImproperlyConfigured(
            "Database configuration missing. Set DATABASE_URL or DB_NAME/DB_USER/DB_PASSWORD."
        )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_name,
            "USER": _db_user,
            "PASSWORD": _db_password,
            "HOST": _db_host,
            "PORT": _db_port,
        }
    }

# ----------------------------------------
# Django REST Framework
# ----------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# ----------------------------------------
# Password validators
# ----------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------
# Internationalization
# ----------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------
# Other settings
# ----------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MAX_POSTE = 3  # nombre maximum de clients simultanés

LOGIN_REDIRECT_URL = 'accounts:redirect_user'
LOGOUT_REDIRECT_URL = 'login_page'

# Mode demo
DEMO_LOGIN_ENABLED = str(config('DEMO_LOGIN_ENABLED', default=str(DEBUG))).lower() in ('1', 'true', 'yes', 'on')
DEMO_USERNAME = config('DEMO_USERNAME', default='demo_salon')
DEMO_PASSWORD = config('DEMO_PASSWORD', default='demo123456')
DEMO_EMAIL = config('DEMO_EMAIL', default='demo@salon.local')
DEMO_SALON_NAME = config('DEMO_SALON_NAME', default='Salon Demo')
